### ISSUE TITLE
factorial of zero

### ISSUE THREAD

**Issue by 81bit23** [vtcbca/basic-programming-81bit23#2]
why factorial of zero is 0

**Comment by 23bit23** [comment]
it is not. factorial of zero is 1.

**Comment by 81bit23** [comment]
i know but my program is giving 0

**Comment by 33bit23** [comment]
Are reeee kya karega re tu...!!

**Comment by 23bit23** [comment]
just add a spacial condition for zero

**Comment by 81bit23** [comment]
ok understood

**Comment by 23bit23** [comment]
factorial of zero  is actually one

**Comment by 76bit23** [comment]
factorial ka matlab kya hai bhai??

**Comment by 81bit23** [comment]
factorial yani ki kisi bhi number ko tum kitne tarike se arrange kar sakte ho.

**Comment by 76bit23** [comment]
kitne tarike se??

**Comment by 23bit23** [comment]
are usi ka to program he bhai

**Comment by 33bit23** [comment]
Acha..!!!
